from . import hostel_base_archive
from . import hostel
from . import hostel_room
from . import hostel_student
from . import hostel_amenities
from . import hostel_categ 
from . import hostel_book
from . import hostel_room_copy
from . import hostel_room_members
from . import hostel_room_availability
from . import res_config_settings
from . import hostel_room_stage
